services:
  auth:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: phantom-auth-dev
    volumes:
#      - phantom-sock:/var/run/phantom
      - ./auth_service:/app/auth_service:ro
      - ./tests:/app/tests:ro
      - ./pytest.ini:/app/pytest.ini:ro
      - ./container-data/auth-db:/var/lib/phantom/auth
      - ./container-data/secrets/development:/run/secrets:ro
    environment:
#      - PHANTOM_DAEMON_SOCKET=/var/run/phantom/daemon.sock
      - AUTH_INACTIVITY_TIMEOUT=1800
    ports:
      - "8443:8443"

volumes:
  phantom-sock:
    external: true
