name: Phantom-WG-MacOS
options:
  bundleIdPrefix: com.remrearas
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  WireGuardKit:
    path: Libraries/WireGuardKit

targets:

  # ── Main App ──────────────────────────────────────────────

  Phantom-WG-MacOS:
    type: application
    platform: macOS
    sources:
      - path: Phantom-WG-MacOS
        excludes:
          - "**/.DS_Store"
          - Assets/pages
          - Localization/translations
      - path: Phantom-WG-MacOS/Localization/translations
        type: folder
        buildPhase: resources
      - path: Phantom-WG-MacOS/Assets/pages
        type: folder
        buildPhase: resources
    dependencies:
      - target: PhantomTunnel
        embed: true
        codeSign: true
      - framework: Libraries/WstunnelKit/libwstunnel_mac.a
        embed: false
    settings:
      base:
        ARCHS: arm64
        ENABLE_HARDENED_RUNTIME: YES
        PRODUCT_NAME: Phantom-WG Mac
        PRODUCT_BUNDLE_IDENTIFIER: com.remrearas.Phantom-WG-MacOS
        INFOPLIST_FILE: Phantom-WG-MacOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: Phantom-WG-MacOS/Phantom-WG-MacOS.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: 9C5SL5H7CM
        SWIFT_OBJC_BRIDGING_HEADER: Phantom-WG-MacOS/BridgingHeader.h
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit/include"
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit"
        OTHER_LDFLAGS:
          - "-lresolv"
          - "-Wl,-w"
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGN_IDENTITY: "Developer ID Application"
        PROVISIONING_PROFILE_SPECIFIER: Mac_Phantom_WG_DeveloperID
      configs:
        Debug:
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: YES
        Release:
          CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
    info:
      path: Phantom-WG-MacOS/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleDisplayName: Phantom-WG Mac
        NSSystemExtensionUsageDescription: "Phantom-WG Mac needs to install a system extension to provide VPN tunnel functionality."
    entitlements:
      path: Phantom-WG-MacOS/Phantom-WG-MacOS.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.application-groups:
          - group.com.remrearas.phantom-wg-macos
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider-systemextension
        com.apple.developer.system-extension.install: true

  # ── Unit Tests (Swift Testing) ────────────────────────────

  PhantomTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: PhantomTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: Phantom-WG-MacOS
    settings:
      base:
        ARCHS: arm64
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Phantom-WG Mac.app/Contents/MacOS/Phantom-WG Mac"
        BUNDLE_LOADER: "$(TEST_HOST)"
        SWIFT_OBJC_BRIDGING_HEADER: ""
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit/include"
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Developer ID Application"
        DEVELOPMENT_TEAM: 9C5SL5H7CM

  # ── Network Extension (System Extension) ─────────────────

  PhantomTunnel:
    type: system-extension
    platform: macOS
    sources:
      - path: PhantomTunnel
        excludes:
          - "**/.DS_Store"
      # Shared files from main app
      - path: Phantom-WG-MacOS/Models/TunnelConfig.swift
      - path: Phantom-WG-MacOS/Models/NETunnelProviderProtocol+Config.swift
      - path: Phantom-WG-MacOS/Models/ConfigStore.swift
      - path: Phantom-WG-MacOS/SharedConstants.swift
      - path: Phantom-WG-MacOS/WstunnelBridge.swift
    dependencies:
      - package: WireGuardKit
        product: WireGuardKit
      - framework: Libraries/WstunnelKit/libwstunnel_mac.a
        embed: false
      - sdk: NetworkExtension.framework
    preBuildScripts:
      - name: Build WireGuard Go Bridge
        script: |
          set -eo pipefail
          if [ -d "/opt/homebrew/opt/go@1.25/libexec" ]; then
            export GOROOT="/opt/homebrew/opt/go@1.25/libexec"
          elif command -v go >/dev/null 2>&1; then
            export GOROOT="$(go env GOROOT)"
          fi
          export PATH="${GOROOT:-}/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
          cd "${PROJECT_DIR}/Libraries/WireGuardKit/Sources/WireGuardKitGo"
          make
        basedOnDependencyAnalysis: false
    settings:
      base:
        ARCHS: arm64
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
        PRODUCT_NAME: com.remrearas.Phantom-WG-MacOS.PhantomTunnel
        PRODUCT_MODULE_NAME: PhantomTunnel
        PRODUCT_BUNDLE_IDENTIFIER: com.remrearas.Phantom-WG-MacOS.PhantomTunnel
        INFOPLIST_FILE: PhantomTunnel/Info.plist
        CODE_SIGN_ENTITLEMENTS: PhantomTunnel/PhantomTunnel.entitlements
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "Developer ID Application"
        DEVELOPMENT_TEAM: 9C5SL5H7CM
        PROVISIONING_PROFILE_SPECIFIER: Mac_PhantomTunnel_DeveloperID
        SWIFT_OBJC_BRIDGING_HEADER: PhantomTunnel/BridgingHeader.h
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit/include"
        OTHER_LDFLAGS:
          - "-lresolv"
          - "-lwstunnel_mac"
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: 1
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit"
          - "$(PROJECT_DIR)/Libraries/WireGuardKit/Sources/WireGuardKitGo/out"
          - "$(CONFIGURATION_BUILD_DIR)"
    info:
      path: PhantomTunnel/Info.plist
      properties:
        CFBundlePackageType: SYSX
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleDisplayName: PhantomTunnel
        NSSystemExtensionUsageDescription: "Phantom-WG Mac needs to install a system extension to provide VPN tunnel functionality."
        NetworkExtension:
          NEProviderClasses:
            com.apple.networkextension.packet-tunnel: $(PRODUCT_MODULE_NAME).PacketTunnelProvider
    entitlements:
      path: PhantomTunnel/PhantomTunnel.entitlements
      properties:
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider-systemextension
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.com.remrearas.phantom-wg-macos
        com.apple.security.network.client: true
        com.apple.security.network.server: true
