name: Phantom-WG
options:
  bundleIdPrefix: com.remrearas
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  WireGuardKit:
    path: Libraries/WireGuardKit

targets:

  # ── Main App ──────────────────────────────────────────────

  Phantom-WG:
    type: application
    platform: iOS
    sources:
      - path: Phantom-WG
        excludes:
          - "**/.DS_Store"
          - Assets/pages
          - Localization/translations
      - path: Phantom-WG/Localization/translations
        type: folder
        buildPhase: resources
      - path: Phantom-WG/Assets/pages
        type: folder
        buildPhase: resources
    dependencies:
      - target: PhantomTunnel
        embed: true
        codeSign: true
        buildPhase:
          copyFiles:
            destination: plugins
      - framework: Libraries/WstunnelKit/libwstunnel_ios.a
        embed: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.remrearas.Phantom-WG
        INFOPLIST_FILE: Phantom-WG/Info.plist
        CODE_SIGN_ENTITLEMENTS: Phantom-WG/Phantom-WG.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 9C5SL5H7CM
        SWIFT_OBJC_BRIDGING_HEADER: Phantom-WG/BridgingHeader.h
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit/include"
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit"
        OTHER_LDFLAGS:
          - "-lresolv"
          - "-Wl,-w"
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
    info:
      path: Phantom-WG/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleDisplayName: Phantom-WG
        UILaunchScreen:
          UIImageName: PhantomLogo
        NSCameraUsageDescription: "Camera access is needed to scan QR codes for tunnel configuration import."
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: Phantom-WG/Phantom-WG.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.remrearas.phantom-wg
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider

  # ── Network Extension ────────────────────────────────────

  PhantomTunnel:
    type: app-extension
    platform: iOS
    sources:
      - path: PhantomTunnel
        excludes:
          - "**/.DS_Store"
      # Shared files from main app
      - path: Phantom-WG/Models/TunnelConfig.swift
      - path: Phantom-WG/Models/TunnelConfig+Keychain.swift
      - path: Phantom-WG/SharedConstants.swift
      - path: Phantom-WG/SharedLogger.swift
      - path: Phantom-WG/WstunnelBridge.swift
      - path: Phantom-WG/Helpers/Keychain.swift
    dependencies:
      - package: WireGuardKit
        product: WireGuardKit
      - framework: Libraries/WstunnelKit/libwstunnel_ios.a
        embed: false
      - sdk: NetworkExtension.framework
    preBuildScripts:
      - name: Build WireGuard Go Bridge
        script: |
          set -eo pipefail
          if [ -d "/opt/homebrew/opt/go@1.25/libexec" ]; then
            export GOROOT="/opt/homebrew/opt/go@1.25/libexec"
          elif command -v go >/dev/null 2>&1; then
            export GOROOT="$(go env GOROOT)"
          fi
          export PATH="${GOROOT:-}/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
          cd "${PROJECT_DIR}/Libraries/WireGuardKit/Sources/WireGuardKitGo"
          make
        basedOnDependencyAnalysis: false
    settings:
      base:
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.remrearas.Phantom-WG.PhantomTunnel
        INFOPLIST_FILE: PhantomTunnel/Info.plist
        CODE_SIGN_ENTITLEMENTS: PhantomTunnel/PhantomTunnel.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 9C5SL5H7CM
        SWIFT_OBJC_BRIDGING_HEADER: PhantomTunnel/BridgingHeader.h
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit/include"
        OTHER_LDFLAGS:
          - "-lresolv"
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: 1
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit"
          - "$(PROJECT_DIR)/Libraries/WireGuardKit/Sources/WireGuardKitGo/out"
          - "$(CONFIGURATION_BUILD_DIR)"
    info:
      path: PhantomTunnel/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleDisplayName: PhantomTunnel
        NSExtension:
          NSExtensionPointIdentifier: com.apple.networkextension.packet-tunnel
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PacketTunnelProvider
    entitlements:
      path: PhantomTunnel/PhantomTunnel.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.remrearas.phantom-wg
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider