name: Phantom-WG-Mac
options:
  bundleIdPrefix: com.remrearas
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  WireGuardKit:
    path: Libraries/WireGuardKit

targets:

  # ── Main App ──────────────────────────────────────────────

  Phantom-WG-Mac:
    type: application
    platform: macOS
    sources:
      - path: Phantom-WG-Mac
        excludes:
          - "**/.DS_Store"
          - Assets/pages
          - Localization/translations
      - path: Phantom-WG-Mac/Localization/translations
        type: folder
        buildPhase: resources
      - path: Phantom-WG-Mac/Assets/pages
        type: folder
        buildPhase: resources
    dependencies:
      - target: PhantomTunnel
        embed: true
        codeSign: true
        buildPhase:
          copyFiles:
            destination: plugins
      - framework: Libraries/WstunnelKit/libwstunnel_mac.a
        embed: false
    settings:
      base:
        ARCHS: arm64
        PRODUCT_BUNDLE_IDENTIFIER: com.remrearas.Phantom-WG-Mac
        INFOPLIST_FILE: Phantom-WG-Mac/Info.plist
        CODE_SIGN_ENTITLEMENTS: Phantom-WG-Mac/Phantom-WG-Mac.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 9C5SL5H7CM
        SWIFT_OBJC_BRIDGING_HEADER: Phantom-WG-Mac/BridgingHeader.h
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit/include"
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit"
        OTHER_LDFLAGS:
          - "-lresolv"
          - "-Wl,-w"
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: 1
    info:
      path: Phantom-WG-Mac/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleDisplayName: Phantom-WG Mac
    entitlements:
      path: Phantom-WG-Mac/Phantom-WG-Mac.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.application-groups:
          - group.com.remrearas.phantom-wg-mac
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider

  # ── Network Extension (App Extension) ────────────────────

  PhantomTunnel:
    type: app-extension
    platform: macOS
    sources:
      - path: PhantomTunnel
        excludes:
          - "**/.DS_Store"
      # Shared files from main app
      - path: Phantom-WG-Mac/Models/TunnelConfig.swift
      - path: Phantom-WG-Mac/Models/TunnelConfig+Keychain.swift
      - path: Phantom-WG-Mac/SharedConstants.swift
      - path: Phantom-WG-Mac/SharedLogger.swift
      - path: Phantom-WG-Mac/WstunnelBridge.swift
      - path: Phantom-WG-Mac/Helpers/Keychain.swift
    dependencies:
      - package: WireGuardKit
        product: WireGuardKit
      - framework: Libraries/WstunnelKit/libwstunnel_mac.a
        embed: false
      - sdk: NetworkExtension.framework
    preBuildScripts:
      - name: Build WireGuard Go Bridge
        script: |
          set -eo pipefail
          if [ -d "/opt/homebrew/opt/go@1.22/libexec" ]; then
            export GOROOT="/opt/homebrew/opt/go@1.22/libexec"
          elif command -v go >/dev/null 2>&1; then
            export GOROOT="$(go env GOROOT)"
          fi
          export PATH="${GOROOT:-}/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
          cd "${PROJECT_DIR}/Libraries/WireGuardKit/Sources/WireGuardKitGo"
          make
        basedOnDependencyAnalysis: false
    settings:
      base:
        ARCHS: arm64
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        PRODUCT_BUNDLE_IDENTIFIER: com.remrearas.Phantom-WG-Mac.PhantomTunnel
        INFOPLIST_FILE: PhantomTunnel/Info.plist
        CODE_SIGN_ENTITLEMENTS: PhantomTunnel/PhantomTunnel.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 9C5SL5H7CM
        SWIFT_OBJC_BRIDGING_HEADER: PhantomTunnel/BridgingHeader.h
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit/include"
        OTHER_LDFLAGS:
          - "-lresolv"
          - "-lwstunnel_mac"
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: 1
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries/WstunnelKit"
          - "$(PROJECT_DIR)/Libraries/WireGuardKit/Sources/WireGuardKitGo/out"
          - "$(CONFIGURATION_BUILD_DIR)"
    info:
      path: PhantomTunnel/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleDisplayName: PhantomTunnel
        NSExtension:
          NSExtensionPointIdentifier: com.apple.networkextension.packet-tunnel
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PacketTunnelProvider
    entitlements:
      path: PhantomTunnel/PhantomTunnel.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.com.remrearas.phantom-wg-mac
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
        com.apple.security.network.client: true
        com.apple.security.network.server: true
