#!/usr/bin/env python3
"""
Phantom-WG Modern — Let's Encrypt Certificate Tool

Obtains or renews a Let's Encrypt certificate for the given domain
and copies it into the mounted secrets directory, replacing the
self-signed certificate generated by 'prod.sh setup'.

This script runs inside a minimal container. It does not start,
stop, or query any services — the operator manages the service
lifecycle around certificate operations.

Usage:
    certbot_obtain.py <domain>

Copyright (c) 2025 Rıza Emre ARAS <r.emrearas@proton.me>
Licensed under AGPL-3.0 - see LICENSE file for details
WireGuard® is a registered trademark of Jason A. Donenfeld.
"""

import os
import shutil
import socket
import subprocess
import sys
from pathlib import Path


# ── Constants ────────────────────────────────────────────────────

SECRETS_DIR = Path("/secrets")
TLS_CERT = SECRETS_DIR / "tls_cert"
TLS_KEY = SECRETS_DIR / "tls_key"

LETSENCRYPT_LIVE = Path("/etc/letsencrypt/live")


# ── Helpers ──────────────────────────────────────────────────────

def log(msg: str, *, error: bool = False) -> None:
    stream = sys.stderr if error else sys.stdout
    print(f"[phantom-certbot] {msg}", file=stream)


def run(cmd: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
    )


# ── Validation ───────────────────────────────────────────────────

def validate_domain(domain: str) -> None:
    """Verify the domain has at least one A or AAAA record."""
    try:
        results = socket.getaddrinfo(domain, None, socket.AF_UNSPEC, socket.SOCK_STREAM)
    except socket.gaierror:
        results = []

    if not results:
        log(f"DNS lookup failed: {domain} has no A/AAAA record", error=True)
        log("Point the domain to this server before requesting a certificate.", error=True)
        sys.exit(1)

    addrs = sorted({r[4][0] for r in results})
    log(f"DNS resolved: {domain} → {', '.join(addrs)}")


def check_certbot() -> str:
    """Return the certbot binary path, or exit if not found."""
    path = shutil.which("certbot")
    if not path:
        log("certbot not found.", error=True)
        sys.exit(1)
    return path


def check_secrets_dir() -> None:
    """Verify the secrets directory is mounted."""
    if not SECRETS_DIR.is_dir():
        log(f"Secrets directory not found: {SECRETS_DIR}", error=True)
        log("Volume mount missing.", error=True)
        sys.exit(1)


def check_root() -> None:
    if os.geteuid() != 0:
        log("This script must be run as root.", error=True)
        sys.exit(1)


# ── Core ─────────────────────────────────────────────────────────

def obtain_certificate(domain: str, certbot: str) -> Path:
    """Run certbot certonly --standalone and return the live directory."""
    log(f"Requesting certificate for {domain}...")

    cmd = [
        certbot, "certonly", "--standalone",
        "-d", domain,
        "--non-interactive",
        "--agree-tos",
        "--register-unsafely-without-email",
        "--keep-until-expiring",
    ]

    email = os.environ.get("CERTBOT_EMAIL")
    if email:
        cmd.extend(["--email", email])
        cmd.remove("--register-unsafely-without-email")

    result = run(cmd)

    if result.returncode != 0:
        log("certbot failed:", error=True)
        if result.stderr:
            for line in result.stderr.strip().splitlines():
                log(f"  {line}", error=True)
        sys.exit(1)

    live_dir = LETSENCRYPT_LIVE / domain
    cert = live_dir / "fullchain.pem"
    key = live_dir / "privkey.pem"

    if not cert.exists() or not key.exists():
        log(f"Certificate files not found in {live_dir}", error=True)
        sys.exit(1)

    log("Certificate obtained successfully.")
    return live_dir


def install_certificate(live_dir: Path) -> None:
    """Copy the certificate and key into the secrets directory."""
    src_cert = live_dir / "fullchain.pem"
    src_key = live_dir / "privkey.pem"

    shutil.copy2(src_cert, TLS_CERT)
    shutil.copy2(src_key, TLS_KEY)

    TLS_KEY.chmod(0o600)
    TLS_CERT.chmod(0o644)

    log(f"Installed: {TLS_CERT}")
    log(f"Installed: {TLS_KEY}")


# ── Main ─────────────────────────────────────────────────────────

def main() -> int:
    if len(sys.argv) != 2 or sys.argv[1] in ("-h", "--help", "help"):
        print(__doc__.strip())
        return 0 if len(sys.argv) > 1 else 2

    domain = sys.argv[1].strip()
    if not domain:
        log("Domain cannot be empty.", error=True)
        return 2

    check_root()
    check_secrets_dir()
    certbot = check_certbot()
    validate_domain(domain)

    live_dir = obtain_certificate(domain, certbot)
    install_certificate(live_dir)

    log("Done. Restart nginx to load the new certificate:")
    log("  ./tools/prod.sh restart nginx")
    return 0


if __name__ == "__main__":
    sys.exit(main())