/*
 * ██████╗ ██╗  ██╗ █████╗ ███╗   ██╗████████╗ ██████╗ ███╗   ███╗
 * ██╔══██╗██║  ██║██╔══██╗████╗  ██║╚══██╔══╝██╔═══██╗████╗ ████║
 * ██████╔╝███████║███████║██╔██╗ ██║   ██║   ██║   ██║██╔████╔██║
 * ██╔═══╝ ██╔══██║██╔══██║██║╚██╗██║   ██║   ██║   ██║██║╚██╔╝██║
 * ██║     ██║  ██║██║  ██║██║ ╚████║   ██║   ╚██████╔╝██║ ╚═╝ ██║
 * ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝    ╚═════╝ ╚═╝     ╚═╝
 *
 * Copyright (c) 2025 Rıza Emre ARAS <r.emrearas@proton.me>
 * Licensed under AGPL-3.0 - see LICENSE file for details
 * Third-party licenses - see THIRD_PARTY_LICENSES file for details
 * WireGuard® is a registered trademark of Jason A. Donenfeld.
 *
 * wireguard_go_bridge.h — v2.1.0 error codes
 * Function prototypes are auto-generated by CGo (//export).
 */

#ifndef WIREGUARD_GO_BRIDGE_H
#define WIREGUARD_GO_BRIDGE_H

#include <stdint.h>
#include <stdlib.h>

/* Error codes */
#define WG_OK                  0
#define WG_ERR_TUN_CREATE     -2
#define WG_ERR_DEVICE_CREATE  -3
#define WG_ERR_IPC_SET        -4
#define WG_ERR_NOT_FOUND      -5
#define WG_ERR_DEVICE_UP      -7
#define WG_ERR_DEVICE_DOWN    -8
#define WG_ERR_INTERNAL       -99

#endif /* WIREGUARD_GO_BRIDGE_H */
