name: Test phantom-daemon

on:
  push:
    branches:
      - dev/daemon

permissions:
  contents: read

jobs:
  test:
    name: Run pytest (container)
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Build dev images
        run: ./tools/dev.sh build

      - name: Generate dev secrets
        run: ./tools/gen-keys-dev.sh

      - name: Start dev stack
        run: ./tools/dev.sh up

      - name: Run tests
        run: ./tools/dev.sh test

      - name: Dev stack logs on failure
        if: failure()
        run: ./tools/dev.sh logs

      - name: Stop dev stack
        if: always()
        run: ./tools/dev.sh down

  e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Build dev images
        run: ./tools/dev.sh build

      - name: Generate dev secrets
        run: ./tools/gen-keys-dev.sh

      - name: Fetch compose-bridge
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./tools/dev.sh fetch-compose-bridge

      - name: Run E2E tests for Multighost
        run: ./tools/dev.sh test-multighost-e2e

      - name: Run E2E tests for Chaos
        run: ./tools/dev.sh test-chaos-e2e
